### PR TITLE
Fix bug of service bus binder connecting to multiple binders.

### PR DESCRIPTION
**Pull request by chenghaoharvey**
## Description
Fix bug of service bus binder connecting to multiple binders following [449a19f](https://github.com/microsoft/spring-cloud-azure/commit/449a19f5bc3fdad8420ef3884be6e45bbb0db8a2). Hopefully you can accept my contribution. 

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [ ] Tests
- [ ] Documentation

## Steps to Test
Steps to test code change

### CODE REVIEW

**Comment by chenghaoharvey** [comment]
Hi, may i know where i can submit SLA in this page

**Comment by warrenzhu25** [comment]
Have you tested the fix?

**Comment by chenghaoharvey** [comment]
> Have you tested the fix?

**Comment by chenghaoharvey** [comment]
yes, i have

**Comment by chenghaoharvey** [comment]
Hi, May i know when can i get a stable version sdk including this change? Because this change will migrate to SNAPSHOT master branch .

**Comment by warrenzhu25** [comment]
`Snapshot` is built daily. For next release, it's still unknown.

**Comment by chenghaoharvey** [comment]
ok, many thanks

**Pull request merged**
