### PR TITLE
Sync doc to generate 6.0 beta3 docs

### PR DESCRIPTION
**Pull request by moarychan**
Upgrade to the Spring Cloud Azure 6.0 beta3.

### CODE REVIEW

**Comment by moarychan** [comment]
Will create PR for the 6.0 beta3 reference doc creation in the MS Doc repo, then sync the update to the branch feature/spring-boot-3 in this repo, but any comments are welcome~

**Comment by saragluna** [comment]
Just one thought, if you don't want to a PR to be reviewed/merged, why not setting it as draft?

**Comment by moarychan** [comment]
> Just one thought, if you don't want to a PR to be reviewed/merged, why not setting it as draft?

This will be the first version of 6.0 in the MS doc repo, so there may be many improvements, this status collects comments for changes, then the subscribers can receive the notification.

**Comment by moarychan** [comment]
As per discussed with @saragluna , the beta3 reference doc will be generated in Github pages due to the MS doc for reference doc 6.0 beta3 being delayed. The 6.0 GA version reference doc will be created on MS doc first, then sync the update to the reference doc of Github pages. 

@saragluna , please help review this PR, thanks!

**Review by saragluna — APPROVED** [review]

**Review by hui1110 — APPROVED** [review]
LGTM

**Pull request merged**
