### PR TITLE
Null ETag Fix App Configuration

### PR DESCRIPTION
**Pull request by mrm9084**
## Description
Set eTag to Null instead of empty String and fixes null check. Added tests.

Fixes: https://github.com/Azure/AppConfiguration/issues/298

### CODE REVIEW

**Comment by saragluna** [comment]
Should the also be applied to 1.1.x?

**Comment by mrm9084** [comment]
Yes it will.

**Comment by Karthickramk** [comment]
Thanks a lot @mrm9084  for fixing this issue. Are we going to release this anytime soon?

**Comment by mrm9084** [comment]
@Karthickramk There should be a release some time this week.

**Comment by Karthickramk** [comment]
Thanks a lot.

**Pull request merged**
