### PR TITLE
improve version display

### PR DESCRIPTION
**Pull request by saragluna**
As title.

### CODE REVIEW

**Comment by stliu** [comment]
> The version for spring-cloud-azure-dependencies is 4.0.0.

This sentence should also be updated

**Comment by stliu** [comment]
https://microsoft.github.io/spring-cloud-azure/current/reference/html/appendix.html#migration-guide-bom one more place should be changed

**Review by chenrujun — APPROVED** [review]
LGTM.

**Comment by chenrujun** [comment]
Closing this PR because we use [azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr) as single source of truth. We should update [azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr) first, then sync to this repo.

**Pull request closed without merging**
