### PR TITLE
Make sure all contents in readme is included for spring security support

### PR DESCRIPTION
**Pull request by chenrujun**
As title.

### CODE REVIEW

**Comment by chenrujun** [comment]
Hi, @backwind1233 , please help to review this PR when you have time.

**Comment by chenrujun** [comment]
Hi, @saragluna , @backwind1233 . Please help to review this PR when you have time.

**Comment by backwind1233** [comment]
I will review this PR today

**Review by saragluna — APPROVED** [review]
LGTM.

**Pull request merged**
